//go:build unit

package env

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/otto-nation/otto-stack/internal/core"
	"github.com/otto-nation/otto-stack/internal/pkg/services"
	"github.com/otto-nation/otto-stack/internal/pkg/types"
	"github.com/stretchr/testify/assert"
)

func TestGenerateFile_Basic(t *testing.T) {
	projectName := "test-project"
	serviceConfigs := []types.ServiceConfig{
		{
			Name: services.ServiceRedis,
			AllEnvironment: map[string]string{
				services.EnvKeyREDIS_HOST: services.EnvRedisREDIS_HOST,
				services.EnvKeyREDIS_PORT: services.EnvRedisREDIS_PORT,
			},
		},
		{
			Name: services.ServicePostgres,
			AllEnvironment: map[string]string{
				services.EnvKeyPOSTGRES_HOST: "localhost",
				services.EnvKeyPOSTGRES_PORT: strconv.Itoa(services.PortPostgres),
			},
		},
	}

	tempFile := filepath.Join(t.TempDir(), core.ExtENV)
	err := GenerateFile(projectName, serviceConfigs, tempFile)
	assert.NoError(t, err)

	content, err := os.ReadFile(tempFile)
	assert.NoError(t, err)
	assert.NotEmpty(t, content)

	contentStr := string(content)
	assert.Contains(t, contentStr, "PROJECT_NAME=test-project")
	assert.Contains(t, contentStr, "COMPOSE_PROJECT_NAME=test-project")
	assert.Contains(t, contentStr, "Generated by otto-stack")
}

func TestGenerateFile_EmptyServices(t *testing.T) {
	projectName := "empty-project"
	serviceConfigs := []types.ServiceConfig{}

	tempFile := filepath.Join(t.TempDir(), core.ExtENV)
	err := GenerateFile(projectName, serviceConfigs, tempFile)
	assert.NoError(t, err)

	content, err := os.ReadFile(tempFile)
	assert.NoError(t, err)
	assert.NotEmpty(t, content)

	contentStr := string(content)
	assert.Contains(t, contentStr, "PROJECT_NAME=empty-project")
}

func TestGenerateFile_ValidFormat(t *testing.T) {
	projectName := "format-test"
	serviceConfigs := []types.ServiceConfig{
		{
			Name: services.ServicePostgres,
			AllEnvironment: map[string]string{
				services.EnvKeyPOSTGRES_HOST: "localhost",
				services.EnvKeyPOSTGRES_PORT: strconv.Itoa(services.PortPostgres),
			},
		},
	}

	tempFile := filepath.Join(t.TempDir(), core.ExtENV)
	err := GenerateFile(projectName, serviceConfigs, tempFile)
	assert.NoError(t, err)

	content, err := os.ReadFile(tempFile)
	assert.NoError(t, err)

	contentStr := string(content)
	lines := strings.Split(contentStr, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			assert.Contains(t, line, "=", "Line should be in KEY=VALUE format: %s", line)
		}
	}
}
