package env

import (
	"strings"
	"testing"

	"github.com/otto-nation/otto-stack/internal/pkg/services"
	"github.com/otto-nation/otto-stack/test/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerate(t *testing.T) {
	t.Run("generates basic environment file", func(t *testing.T) {
		projectName := "test-project"
		serviceNames := []string{"redis", "postgres"}

		manager, err := services.New()
		require.NoError(t, err)

		content, err := Generate(projectName, serviceNames, manager)
		assert.NoError(t, err)
		assert.NotEmpty(t, content)

		contentStr := string(content)

		// Check for project configuration
		assert.Contains(t, contentStr, "PROJECT_NAME=test-project")
		assert.Contains(t, contentStr, "COMPOSE_PROJECT_NAME=test-project")

		// Check for header comment
		assert.Contains(t, contentStr, "Generated by otto-stack")
		assert.Contains(t, contentStr, "Project: test-project")
	})

	t.Run("handles empty services list", func(t *testing.T) {
		projectName := "empty-project"
		services := []string{}

		content, err := Generate(projectName, services, testutil.NewTestManager(t))
		assert.NoError(t, err)
		assert.NotEmpty(t, content)

		contentStr := string(content)
		assert.Contains(t, contentStr, "PROJECT_NAME=empty-project")
	})

	t.Run("handles empty project name", func(t *testing.T) {
		projectName := ""
		services := []string{"redis"}

		content, err := Generate(projectName, services, testutil.NewTestManager(t))
		assert.NoError(t, err)
		assert.NotEmpty(t, content)

		contentStr := string(content)
		assert.Contains(t, contentStr, "PROJECT_NAME=")
		assert.Contains(t, contentStr, "COMPOSE_PROJECT_NAME=")
	})

	t.Run("generates valid environment format", func(t *testing.T) {
		projectName := "format-test"
		services := []string{"test-service"}

		content, err := Generate(projectName, services, testutil.NewTestManager(t))
		assert.NoError(t, err)

		contentStr := string(content)
		lines := strings.Split(contentStr, "\n")

		// Check that non-comment, non-empty lines follow KEY=VALUE format
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line != "" && !strings.HasPrefix(line, "#") {
				assert.Contains(t, line, "=", "Line should be in KEY=VALUE format: %s", line)
			}
		}
	})

	t.Run("includes timestamp in header", func(t *testing.T) {
		projectName := "timestamp-test"
		services := []string{}

		content, err := Generate(projectName, services, testutil.NewTestManager(t))
		assert.NoError(t, err)

		contentStr := string(content)
		assert.Contains(t, contentStr, "Generated by otto-stack on")
	})
}

func TestAddServiceEnv(t *testing.T) {
	t.Run("handles nonexistent service gracefully", func(t *testing.T) {
		var content strings.Builder

		// Should not panic or error
		addServiceEnv(&content, "nonexistent-service", testutil.NewTestManager(t))

		// Content should remain empty for nonexistent service
		assert.Empty(t, content.String())
	})

	t.Run("processes service name correctly", func(t *testing.T) {
		var content strings.Builder

		// Test with various service names
		testServices := []string{"redis", "postgres", "mysql"}

		for _, service := range testServices {
			addServiceEnv(&content, service, testutil.NewTestManager(t))
		}

		// Should not panic and content should be string
		result := content.String()
		assert.IsType(t, "", result)
	})
}
