package env

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/otto-nation/otto-stack/internal/pkg/services"
	"gopkg.in/yaml.v3"
)

// Generate creates environment file content for services
func Generate(projectName string, services []string) ([]byte, error) {
	var content strings.Builder

	fmt.Fprintf(&content, "# Generated by otto-stack on %s\n", time.Now().Format(time.RFC1123))
	fmt.Fprintf(&content, "# Project: %s\n\n", projectName)
	fmt.Fprintf(&content, "PROJECT_NAME=%s\n", projectName)
	fmt.Fprintf(&content, "COMPOSE_PROJECT_NAME=%s\n\n", projectName)

	for _, serviceName := range services {
		addServiceEnv(&content, serviceName)
	}

	return []byte(content.String()), nil
}

func addServiceEnv(content *strings.Builder, serviceName string) {
	yamlPath := filepath.Join(services.ServicesDir, "**", serviceName+".yaml")
	matches, _ := filepath.Glob(yamlPath)
	if len(matches) == 0 {
		return
	}

	data, err := os.ReadFile(matches[0])
	if err != nil {
		return
	}

	var service services.ServiceConfig
	if err := yaml.Unmarshal(data, &service); err != nil {
		return
	}

	if len(service.Environment) > 0 {
		fmt.Fprintf(content, "# %s\n", strings.ToUpper(serviceName))
		for key, value := range service.Environment {
			fmt.Fprintf(content, "%s=%v\n", key, value)
		}
		content.WriteString("\n")
	}
}
