package env

import (
	"fmt"
	"strings"
	"time"

	"github.com/otto-nation/otto-stack/internal/pkg/services"
)

// Generate creates environment file content for services
func Generate(projectName string, services []string) ([]byte, error) {
	var content strings.Builder

	fmt.Fprintf(&content, "# Generated by otto-stack on %s\n", time.Now().Format(time.RFC1123))
	fmt.Fprintf(&content, "# Project: %s\n\n", projectName)
	fmt.Fprintf(&content, "PROJECT_NAME=%s\n", projectName)
	fmt.Fprintf(&content, "COMPOSE_PROJECT_NAME=%s\n\n", projectName)

	for _, serviceName := range services {
		addServiceEnv(&content, serviceName)
	}

	return []byte(content.String()), nil
}

func addServiceEnv(content *strings.Builder, serviceName string) {
	manager, err := services.New()
	if err != nil {
		return
	}

	service, err := manager.GetService(serviceName)
	if err != nil {
		return
	}

	// Add environment variables from the service
	if len(service.Environment) > 0 || len(service.Container.Environment) > 0 {
		fmt.Fprintf(content, "# %s\n", strings.ToUpper(serviceName))

		// Add top-level environment variables
		for key, value := range service.Environment {
			fmt.Fprintf(content, "%s=%v\n", key, value)
		}

		// Add container-level environment variables
		for key, value := range service.Container.Environment {
			fmt.Fprintf(content, "%s=%v\n", key, value)
		}

		content.WriteString("\n")
	}
}
