package env

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/otto-nation/otto-stack/internal/pkg/constants"
	"gopkg.in/yaml.v3"
)

// Generator handles .env file generation using service YAML data
type Generator struct {
	projectName string
	environment string
}

// ServiceYAML represents a service configuration (simplified)
type ServiceYAML struct {
	Name        string         `yaml:"name"`
	Description string         `yaml:"description"`
	Environment map[string]any `yaml:"environment"`
}

// NewGenerator creates a new env generator
func NewGenerator(projectName, environment string) *Generator {
	return &Generator{
		projectName: projectName,
		environment: environment,
	}
}

// Generate creates environment file content for only the enabled services
func (g *Generator) Generate(services []string) ([]byte, error) {
	var content strings.Builder

	// Header
	content.WriteString("# Generated by otto-stack\n")
	content.WriteString(fmt.Sprintf("# Project: %s\n", g.projectName))
	content.WriteString(fmt.Sprintf("# Generated on: %s\n", time.Now().Format(time.RFC1123)))
	content.WriteString("#\n")
	content.WriteString("# This file contains environment variables for all configured services.\n")
	content.WriteString("# You can override any of these values by creating a .env.local file.\n\n")

	// Project configuration
	content.WriteString("# ============================================================================\n")
	content.WriteString("# PROJECT CONFIGURATION\n")
	content.WriteString("# ============================================================================\n")
	content.WriteString(fmt.Sprintf("PROJECT_NAME=%s\n", g.projectName))
	content.WriteString(fmt.Sprintf("ENVIRONMENT=%s\n", g.environment))
	content.WriteString(fmt.Sprintf("COMPOSE_PROJECT_NAME=%s\n\n", g.projectName))

	// Add environment variables for enabled services only
	for _, serviceName := range services {
		if err := g.addServiceEnv(&content, serviceName); err != nil {
			// Log error but continue with other services
			continue
		}
	}

	return []byte(content.String()), nil
}

// addServiceEnv adds environment variables for a specific service by reading its YAML
func (g *Generator) addServiceEnv(content *strings.Builder, serviceName string) error {
	// Find and load the service YAML file
	serviceFile, err := g.findServiceFile(serviceName)
	if err != nil {
		return err
	}

	data, err := os.ReadFile(serviceFile)
	if err != nil {
		return err
	}

	var service ServiceYAML
	if err := yaml.Unmarshal(data, &service); err != nil {
		return err
	}

	// Only add section if service has environment variables
	if len(service.Environment) == 0 {
		return nil
	}

	content.WriteString("# ============================================================================\n")
	fmt.Fprintf(content, "# %s (%s)\n", strings.ToUpper(service.Name), service.Description)
	content.WriteString("# ============================================================================\n")

	// Add environment variables
	for key, value := range service.Environment {
		if strValue, ok := value.(string); ok {
			fmt.Fprintf(content, "%s=%s\n", key, strValue)
		}
	}
	content.WriteString("\n")

	return nil
}

// findServiceFile finds the YAML file for a given service name
func (g *Generator) findServiceFile(serviceName string) (string, error) {
	servicesDir := "internal/config/services"
	var foundFile string

	err := filepath.Walk(servicesDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !constants.IsYAMLFile(path) {
			return nil
		}

		// Check if filename matches service name
		filename := strings.TrimSuffix(filepath.Base(path), ".yaml")
		if filename == serviceName {
			foundFile = path
			return filepath.SkipDir // Stop walking once found
		}

		return nil
	})

	if err != nil {
		return "", err
	}

	if foundFile == "" {
		return "", fmt.Errorf("service file not found for: %s", serviceName)
	}

	return foundFile, nil
}
