# golangci-lint configuration for otto-stack
# Minimal configuration for golangci-lint v2.x
# Binary version: v2.4.0 (keep in sync with Taskfile.yml GOLANGCI_LINT_VERSION)

version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - iface
    - importas
    - inamedparam
    - goconst
    - modernize
    - unparam
    - mnd
    - nestif
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
      - path: "test_helpers.go"
        linters:
          - errcheck
          - unused
      - path: "cmd/generate-*"
        linters:
          - unused
      - path: "internal/pkg/constants/templates.go"
        linters:
          - lll
      - path: "internal/scripts/embedded.go"
        linters:
          - nestif

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
