name: localstack-init
description: LocalStack AWS resource initialization service
category: cloud
visibility: hidden

dependencies:
  required:
  - localstack-core
  soft: []
  conflicts: []
  provides:
  - aws-resource-init

docker:
  image: amazon/aws-cli:latest
  restart: "no"
  command:
    - "sh"
    - "-c"
    - "apk add --no-cache yq curl && chmod +x /scripts/localstack-init.sh && /scripts/localstack-init.sh"
  simple_volumes:
    - ./otto-stack/otto-stack-config.yml:/config/otto-stack-config.yml:ro
    - ./otto-stack/scripts:/scripts:ro

service_configuration:
  - name: docker_image
    type: string
    description: Docker image to use for AWS CLI initialization
    default: amazon/aws-cli:latest
    example: amazon/aws-cli:2.13.0
    required: false

documentation:
  examples:
    - "aws --endpoint-url=http://localhost:4566 sqs list-queues"
    - "aws --endpoint-url=http://localhost:4566 sns list-topics"
  usage_notes: "Dynamically initializes AWS resources based on otto-stack configuration and service overrides"
  links:
    - "https://docs.localstack.cloud/"
  use_cases:
    - Automatic AWS resource creation based on enabled services
    - Configurable SQS queues, SNS topics, and S3 buckets
    - Project-specific resource naming
