name: localstack-core
description: LocalStack core AWS service emulator
category: cloud
type: container
visibility: hidden
dependencies:
  required: []
  soft: []
  conflicts: []
  provides:
    - aws-emulation
    - cloud-core
documentation:
  examples:
    - aws --endpoint-url=http://localhost:4566 s3 ls
  usage_notes: Core LocalStack service providing AWS API emulation for local development
  links:
    - https://docs.localstack.cloud/
  web_interfaces:
    - name: LocalStack Dashboard
      url: http://localhost:${LOCALSTACK_DASHBOARD_PORT:-8055}
      description: LocalStack web dashboard
  use_cases:
    - AWS service emulation for local development
    - Cloud service testing without AWS costs
    - Offline development environment
docker:
  image: localstack/localstack:latest
  restart: unless-stopped
  networks:
    - otto-stack
  memory_limit: 512m
  environment:
    - LOCALSTACK_HOST=localhost
    - LOCALSTACK_PORT=${LOCALSTACK_PORT:-4566}
    - LOCALSTACK_DASHBOARD_PORT=${LOCALSTACK_DASHBOARD_PORT:-8055}
    - LOCALSTACK_URL=http://localhost:${LOCALSTACK_PORT:-4566}
    - AWS_ENDPOINT_URL=http://localhost:${LOCALSTACK_PORT:-4566}
    - AWS_ACCESS_KEY_ID=test
    - AWS_SECRET_ACCESS_KEY=test
    - AWS_DEFAULT_REGION=us-east-1
    - SERVICES=
    - DEBUG=1
    - PERSISTENCE=1
    - LAMBDA_EXECUTOR=docker
    - DOCKER_HOST=unix:///var/run/docker.sock
  health_check:
    test:
      - CMD
      - curl
      - -f
      - http://localhost:4566/_localstack/health
    interval: 30s
    timeout: 10s
    retries: 5
    start_period: 30s
service_configuration:
  - name: docker_image
    type: string
    description: Docker image to use for LocalStack container
    default: localstack/localstack:latest
    example: localstack/localstack:2.3
    required: false
  - name: port
    type: integer
    description: Port number for LocalStack API endpoint
    default: "4566"
    example: "4567"
    required: false
  - name: dashboard_port
    type: integer
    description: Port number for LocalStack dashboard
    default: "8055"
    example: "8056"
    required: false
  - name: memory_limit
    type: string
    description: Memory limit for LocalStack container
    default: 512m
    example: 1g
    required: false
  - name: persistence
    type: boolean
    description: Enable LocalStack data persistence
    default: "true"
    example: "false"
    required: false
