package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/otto-nation/otto-stack/internal/config"
	pkgConfig "github.com/otto-nation/otto-stack/internal/pkg/config"
	"gopkg.in/yaml.v3"
)

func main() {
	var commandConfig pkgConfig.CommandConfig
	if err := yaml.Unmarshal(config.EmbeddedCommandsYAML, &commandConfig); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Failed to parse commands.yaml: %v\n", err)
		os.Exit(1)
	}

	file, err := os.Create("internal/pkg/cli/commands_generated.go")
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Failed to create file: %v\n", err)
		os.Exit(1)
	}
	defer func() {
		if err := file.Close(); err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "Failed to close file: %v\n", err)
		}
	}()

	// Generate minimal working commands file
	_, _ = fmt.Fprintln(file, "// Code generated by generate-commands. DO NOT EDIT.")
	_, _ = fmt.Fprintln(file, "package cli")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "import (")
	_, _ = fmt.Fprintln(file, "\t\"context\"")
	_, _ = fmt.Fprintln(file, "\t\"log/slog\"")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "\t\"github.com/otto-nation/otto-stack/internal/core/services\"")
	_, _ = fmt.Fprintln(file, "\t\"github.com/otto-nation/otto-stack/internal/pkg/cli/handlers/project\"")
	_, _ = fmt.Fprintln(file, "\t\"github.com/otto-nation/otto-stack/internal/pkg/cli/handlers/stack\"")
	_, _ = fmt.Fprintln(file, "\t\"github.com/otto-nation/otto-stack/internal/pkg/constants\"")
	_, _ = fmt.Fprintln(file, "\t\"github.com/otto-nation/otto-stack/internal/pkg/types\"")
	_, _ = fmt.Fprintln(file, "\t\"github.com/otto-nation/otto-stack/internal/pkg/ui\"")
	_, _ = fmt.Fprintln(file, "\t\"github.com/spf13/cobra\"")
	_, _ = fmt.Fprintln(file, ")")
	_, _ = fmt.Fprintln(file)

	// Generate command functions with proper handlers
	for name, cmd := range commandConfig.Commands {
		funcName := fmt.Sprintf("New%sCommand", toPascalCase(name))
		_, _ = fmt.Fprintf(file, "func %s(serviceManager *services.Manager, logger *slog.Logger) *cobra.Command {\n", funcName)

		// Create handler based on command type
		switch cmd.Handler {
		case "stack":
			_, _ = fmt.Fprintf(file, "\thandler := stack.New%sHandler()\n", toPascalCase(name))
		case "project":
			if name == "version" {
				_, _ = fmt.Fprintln(file, "\thandler := project.NewVersionHandler()")
			} else {
				_, _ = fmt.Fprintln(file, "\thandler := project.NewVersionHandler() // TODO: specific handler")
			}
		default:
			_, _ = fmt.Fprintln(file, "\t// TODO: handler implementation")
		}

		_, _ = fmt.Fprintln(file, "\treturn &cobra.Command{")
		_, _ = fmt.Fprintf(file, "\t\tUse:   constants.Command%s,\n", toPascalCase(name))
		_, _ = fmt.Fprintf(file, "\t\tShort: \"%s\",\n", escape(cmd.Description))
		if cmd.LongDescription != "" {
			_, _ = fmt.Fprintf(file, "\t\tLong:  \"%s\",\n", escape(cmd.LongDescription))
		}
		_, _ = fmt.Fprintln(file, "\t\tRunE: func(cmd *cobra.Command, args []string) error {")
		_, _ = fmt.Fprintln(file, "\t\t\tctx := context.Background()")
		_, _ = fmt.Fprintln(file, "\t\t\treturn handler.Handle(ctx, cmd, args, &types.BaseCommand{")
		_, _ = fmt.Fprintln(file, "\t\t\t\tManager: &serviceManagerAdapter{serviceManager},")
		_, _ = fmt.Fprintln(file, "\t\t\t\tLogger:  &loggerAdapter{logger},")
		_, _ = fmt.Fprintln(file, "\t\t\t\tOutput:  &outputAdapter{ui.NewOutput()},")
		_, _ = fmt.Fprintln(file, "\t\t\t})")
		_, _ = fmt.Fprintln(file, "\t\t},")
		_, _ = fmt.Fprintln(file, "\t}")
		_, _ = fmt.Fprintln(file, "}")
		_, _ = fmt.Fprintln(file)
	}

	// Generate adapters
	generateAdapters(file)

	fmt.Printf("Generated %d commands\n", len(commandConfig.Commands))
}

func generateAdapters(file *os.File) {
	// Service Manager Adapter
	_, _ = fmt.Fprintln(file, "type serviceManagerAdapter struct {")
	_, _ = fmt.Fprintln(file, "\tmanager *services.Manager")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (s *serviceManagerAdapter) StartServices(ctx context.Context, serviceNames []string, options types.StartOptions) error {")
	_, _ = fmt.Fprintln(file, "\treturn s.manager.StartServices(ctx, serviceNames, options)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (s *serviceManagerAdapter) StopServices(ctx context.Context, serviceNames []string, options types.StopOptions) error {")
	_, _ = fmt.Fprintln(file, "\treturn s.manager.StopServices(ctx, serviceNames, options)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (s *serviceManagerAdapter) GetServiceStatus(ctx context.Context, serviceNames []string) ([]types.ServiceStatus, error) {")
	_, _ = fmt.Fprintln(file, "\treturn s.manager.GetServiceStatus(ctx, serviceNames)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	// Logger Adapter
	_, _ = fmt.Fprintln(file, "type loggerAdapter struct {")
	_, _ = fmt.Fprintln(file, "\tlogger *slog.Logger")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (l *loggerAdapter) Info(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\tl.logger.Info(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (l *loggerAdapter) Error(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\tl.logger.Error(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (l *loggerAdapter) Debug(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\tl.logger.Debug(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	// Output Adapter
	_, _ = fmt.Fprintln(file, "type outputAdapter struct {")
	_, _ = fmt.Fprintln(file, "\toutput *ui.Output")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (o *outputAdapter) Success(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\to.output.Success(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (o *outputAdapter) Error(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\to.output.Error(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (o *outputAdapter) Warning(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\to.output.Warning(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (o *outputAdapter) Info(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\to.output.Info(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (o *outputAdapter) Header(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\to.output.Header(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "func (o *outputAdapter) Muted(msg string, args ...any) {")
	_, _ = fmt.Fprintln(file, "\to.output.Muted(msg, args...)")
	_, _ = fmt.Fprintln(file, "}")
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "-")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func escape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}
