name: kafka-topics
description: Kafka topic initialization and management service
category: messaging
visibility: hidden

dependencies:
  required:
  - kafka-broker
  soft: []
  conflicts: []
  provides:
  - topic-management

docker:
  image: confluentinc/cp-kafka:latest
  restart: "no"
  command:
    - "sh"
    - "-c"
    - "chmod +x /scripts/kafka-topics-init.sh && /scripts/kafka-topics-init.sh"
  simple_volumes:
    - ./otto-stack/otto-stack-config.yml:/config/otto-stack-config.yml:ro
    - ./otto-stack/scripts:/scripts:ro

service_configuration:
  - name: docker_image
    type: string
    description: Docker image to use for Kafka topics initialization
    default: confluentinc/cp-kafka:latest
    example: confluentinc/cp-kafka:7.4.0
    required: false

documentation:
  examples:
    - "kafka-topics --bootstrap-server localhost:9092 --list"
  usage_notes: "Dynamically creates Kafka topics based on otto-stack configuration and service overrides"
  links:
    - "https://kafka.apache.org/documentation/"
  use_cases:
    - Automatic Kafka topic creation based on configuration
    - Configurable topic names, partitions, and replication
    - Project-specific topic naming
