package codegen

import (
	"fmt"
	"os"
	"strings"

	pkgerrors "github.com/otto-nation/otto-stack/internal/pkg/errors"
)

// MessageConstant represents a generated message constant
type MessageConstant struct {
	Name  string
	Value string
}

// MessageGroup represents a group of related messages
type MessageGroup struct {
	Name      string
	Constants []MessageConstant
}

// GenerateMessages generates Go constants from messages.yaml
func GenerateMessages(messagesPath, outputPath string) error {
	// Load messages.yaml
	messages, err := LoadYAMLConfig(messagesPath)
	if err != nil {
		return pkgerrors.NewConfigError(pkgerrors.ErrCodeOperationFail, "messages", "failed to load messages.yaml", err)
	}

	// Parse messages into groups
	groups := parseMessageGroups(messages)

	// Generate Go file
	return generateMessagesFile(groups, outputPath)
}

func parseMessageGroups(messages map[string]any) []MessageGroup {
	var groups []MessageGroup

	for groupName, groupData := range messages {
		groupMap, ok := groupData.(map[string]any)
		if !ok {
			continue
		}

		group := MessageGroup{Name: ToPascalCase(groupName)}

		for key, value := range groupMap {
			strValue, ok := value.(string)
			if !ok {
				continue
			}

			constName := ToPascalCase(groupName) + ToPascalCase(key)
			group.Constants = append(group.Constants, MessageConstant{
				Name:  constName,
				Value: strValue,
			})
		}

		if len(group.Constants) > 0 {
			groups = append(groups, group)
		}
	}

	return groups
}

func generateMessagesFile(groups []MessageGroup, outputPath string) error {
	var sb strings.Builder

	// Header
	sb.WriteString("// Code generated by cmd/codegen/generate_messages.go. DO NOT EDIT.\n\n")
	sb.WriteString("package messages\n\n")

	// Generate constants for each group
	for _, group := range groups {
		sb.WriteString(fmt.Sprintf("// %s messages\n", group.Name))
		sb.WriteString("const (\n")
		for _, constant := range group.Constants {
			sb.WriteString(fmt.Sprintf("\t%s = %q\n", constant.Name, constant.Value))
		}
		sb.WriteString(")\n\n")
	}

	// Write to file
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return pkgerrors.NewConfigError(pkgerrors.ErrCodeOperationFail, "output", "failed to write messages file", err)
	}

	return nil
}
