package core

import (
	"path/filepath"
)

// Application constants
const (
	AppName      = "otto-stack"
	AppNameTitle = "Otto Stack"
	GitHubOrg    = "otto-nation"
	GitHubRepo   = "otto-stack"
)

// Exit codes
const (
	ExitSuccess = 0
	ExitError   = 1
)

// Timeout constants
const (
	DefaultStartTimeoutSeconds = 30
	DefaultHTTPTimeoutSeconds  = 5
)

// Threshold constants
const (
	HTTPOKStatusThreshold = 400
	MinArgumentCount      = 1
	DefaultLogTailLines   = "100"
	MinProjectNameLength  = 2
	MaxProjectNameLength  = 50
)

// File names
const (
	EnvGeneratedFileName = ".env.generated"
	EnvGeneratedFilePath = OttoStackDir + "/" + GeneratedDir + "/" + EnvGeneratedFileName
	ReadmeFileName       = "README.md"
	GitIgnoreFileName    = ".gitignore"
)

// URLs
const (
	DocsURL = "https://otto-nation.github.io/otto-stack"
)

// Actions
const (
	ActionProceed = "proceed"
	ActionBack    = "back"
)

// Prompts
const (
	PromptProjectName = "Enter project name"
	HelpProjectName   = "The name of your project (alphanumeric and hyphens only)"
)

// File permissions
const (
	PermReadWriteExec = 0755
	PermReadWrite     = 0644
)

// File extension constants
const (
	ExtYAML          = ".yaml"
	ExtYML           = ".yml"
	ExtJSON          = ".json"
	ExtENV           = ".env"
	ExtSH            = ".sh"
	ExtMD            = ".md"
	YMLFileExtension = ExtYML // Alias for compatibility
)

// Otto Stack directory and file constants
const (
	OttoStackDir        = ".otto-stack"
	SharedDir           = "shared"
	ConfigFileName      = "config.yaml"
	LocalConfigFileName = "config.local.yaml"
	ServiceConfigsDir   = "services"
	GeneratedDir        = "generated"
	LocalFileExtension  = ".local"
	SharedRegistryFile  = "containers.yaml"
)

// Container naming constants
const (
	SharedContainerPrefix = AppName + "-"
)

// Docker command constants
const (
	DockerCmdPs    = "ps"
	DockerCmdLogs  = "logs"
	DockerCmdExec  = "exec"
	DockerCmdStop  = "stop"
	DockerCmdStart = "start"
	DockerCmdRm    = "rm"
	DockerCmdPull  = "pull"
	DockerCmdBuild = "build"
)

// Generated file header comments
const (
	GeneratedFileHeader        = "# Generated by otto-stack - DO NOT EDIT MANUALLY\n"
	ComposeHeaderShared        = GeneratedFileHeader + "# This file contains shared services used across multiple projects\n# Managed via: otto-stack status --shared\n\n"
	ComposeHeaderProject       = GeneratedFileHeader + "\n"
	ComposeHeaderProjectShared = GeneratedFileHeader + "# This file contains project-specific services only\n# Shared services are located at: %s/docker-compose.yml\n\n"
	EnvGeneratedHeader         = GeneratedFileHeader + "# Generated on %s\n"
	RegistryHeader             = GeneratedFileHeader + "# This file tracks shared containers across projects\n\n"
)

// HTTP status constants
const (
	HTTPStatusOK                  = 200
	HTTPStatusBadRequest          = 400
	HTTPStatusUnauthorized        = 401
	HTTPStatusForbidden           = 403
	HTTPStatusNotFound            = 404
	HTTPStatusInternalServerError = 500
)

// Common environment variable names
const (
	EnvVarPATH            = "PATH"
	EnvVarHOME            = "HOME"
	EnvVarUSER            = "USER"
	EnvVarTERM            = "TERM"
	EnvOttoNonInteractive = "OTTO_NON_INTERACTIVE"
)

// IsYAMLFile checks if a filename has a YAML extension
func IsYAMLFile(filename string) bool {
	ext := filepath.Ext(filename)
	return ext == ExtYAML || ext == ExtYML
}

// TrimYAMLExt removes the YAML extension from a filename
func TrimYAMLExt(filename string) string {
	if filepath.Ext(filename) == ExtYAML {
		return filename[:len(filename)-len(ExtYAML)]
	}
	if filepath.Ext(filename) == ExtYML {
		return filename[:len(filename)-len(ExtYML)]
	}
	return filename
}
