package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/otto-nation/otto-stack/internal/config"
	pkgConfig "github.com/otto-nation/otto-stack/internal/pkg/config"
	"github.com/otto-nation/otto-stack/internal/pkg/constants"
	"gopkg.in/yaml.v3"
)

type FlagMetadata struct {
	Name        string
	Type        string
	Short       string
	Description string
	Default     any
	Options     []string
	Commands    []string
	IsGlobal    bool
}

func main() {
	commandConfig, err := loadConfig()
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Failed to load config: %v\n", err)
		os.Exit(1)
	}

	// Template-based generation (disabled for now to avoid conflicts)
	// if err := generateWithTemplates(commandConfig); err != nil {
	// 	_, _ = fmt.Fprintf(os.Stderr, "Failed to generate with templates: %v\n", err)
	// 	os.Exit(1)
	// }

	// Keep legacy generation for now (can be removed later)
	flagMetadata := collectFlagMetadata(commandConfig)
	messageMetadata := collectMessageMetadata(commandConfig)
	iconMetadata := collectIconMetadata(commandConfig)

	if err := generateCLIFile(flagMetadata, messageMetadata, iconMetadata, commandConfig); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Failed to generate CLI file: %v\n", err)
		os.Exit(1)
	}
}

func loadConfig() (*pkgConfig.CommandConfig, error) {
	var commandConfig pkgConfig.CommandConfig
	if err := yaml.Unmarshal(config.EmbeddedCommandsYAML, &commandConfig); err != nil {
		return nil, fmt.Errorf("failed to parse commands.yaml: %w", err)
	}
	return &commandConfig, nil
}

func collectFlagMetadata(commandConfig *pkgConfig.CommandConfig) map[string]*FlagMetadata {
	flagMetadata := make(map[string]*FlagMetadata)

	// Process global flags
	for flagName, flag := range commandConfig.Global.Flags {
		flagMetadata[flagName] = &FlagMetadata{
			Name:        flagName,
			Type:        flag.Type,
			Short:       flag.Short,
			Description: flag.Description,
			Default:     flag.Default,
			Options:     flag.Options,
			Commands:    []string{},
			IsGlobal:    true,
		}
	}

	// Process command-specific flags
	for cmdName, command := range commandConfig.Commands {
		for flagName, flag := range command.Flags {
			if existing, exists := flagMetadata[flagName]; exists {
				existing.Commands = append(existing.Commands, cmdName)
			} else {
				flagMetadata[flagName] = &FlagMetadata{
					Name:        flagName,
					Type:        flag.Type,
					Short:       flag.Short,
					Description: flag.Description,
					Default:     flag.Default,
					Options:     flag.Options,
					Commands:    []string{cmdName},
					IsGlobal:    false,
				}
			}
		}
	}

	// Sort commands for consistent output
	for _, metadata := range flagMetadata {
		sort.Strings(metadata.Commands)
	}

	return flagMetadata
}

func generateCLIFile(flagMetadata map[string]*FlagMetadata, messageMetadata map[string]string, iconMetadata map[string]string, commandConfig *pkgConfig.CommandConfig) error {
	if len(flagMetadata) == 0 {
		return fmt.Errorf("no flags found in configuration")
	}

	file, err := os.Create(CLIOutputPath)
	if err != nil {
		return fmt.Errorf("failed to create CLI file: %w", err)
	}
	defer func() { _ = file.Close() }()

	writeFileHeader(file)
	writeFlagStruct(file)
	writeFlagConstants(file, flagMetadata)
	writeMessageConstants(file, messageMetadata)
	writeCommandConstants(file, commandConfig)
	writeFlagMetadataMap(file, flagMetadata)
	writeMessageMetadataMap(file, messageMetadata)
	writeIconMetadataMap(file, iconMetadata)
	writeCommandMetadataMap(file, commandConfig)
	writeHelperFunctions(file)

	// Add parsers to same file
	for cmdName, cmd := range commandConfig.Commands {
		writeCommandParser(file, cmdName, cmd, commandConfig)
	}

	fmt.Printf("Generated CLI code for %d flags and %d commands\n", len(flagMetadata), len(commandConfig.Commands))
	return nil
}

func writeFileHeader(file *os.File) {
	_, _ = fmt.Fprintln(file, "// Code generated by cmd/generate-cli. DO NOT EDIT.")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "package constants")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "import (")
	_, _ = fmt.Fprintln(file, "\t\"fmt\"")
	_, _ = fmt.Fprintln(file, "\t\"reflect\"")
	_, _ = fmt.Fprintln(file, "\t\"time\"")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "\t\"github.com/spf13/cobra\"")
	_, _ = fmt.Fprintln(file, ")")
	_, _ = fmt.Fprintln(file)
}

func writeFlagStruct(file *os.File) {
	_, _ = fmt.Fprintln(file, "// FlagInfo contains metadata about a command flag")
	_, _ = fmt.Fprintln(file, "type FlagInfo struct {")
	_, _ = fmt.Fprintln(file, "\tName        string")
	_, _ = fmt.Fprintln(file, "\tType        string")
	_, _ = fmt.Fprintln(file, "\tShort       string")
	_, _ = fmt.Fprintln(file, "\tDescription string")
	_, _ = fmt.Fprintln(file, "\tDefault     interface{}")
	_, _ = fmt.Fprintln(file, "\tOptions     []string")
	_, _ = fmt.Fprintln(file, "\tCommands    []string")
	_, _ = fmt.Fprintln(file, "\tIsGlobal    bool")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "// CommandInfo contains metadata about a command")
	_, _ = fmt.Fprintln(file, "type CommandInfo struct {")
	_, _ = fmt.Fprintln(file, "\tName        string")
	_, _ = fmt.Fprintln(file, "\tCategory    string")
	_, _ = fmt.Fprintln(file, "\tHandler     string")
	_, _ = fmt.Fprintln(file, "\tDescription string")
	_, _ = fmt.Fprintln(file, "\tFlags       []string")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)
}

func writeFlagConstants(file *os.File, flagMetadata map[string]*FlagMetadata) {
	_, _ = fmt.Fprintln(file, "// Flag name constants")
	_, _ = fmt.Fprintln(file, "const (")

	flagNames := getSortedFlagNames(flagMetadata)
	for _, flagName := range flagNames {
		constName := "Flag" + toPascalCase(flagName)
		_, _ = fmt.Fprintf(file, "\t%s = %q\n", constName, flagName)
	}
	_, _ = fmt.Fprintln(file, ")")
	_, _ = fmt.Fprintln(file)
}

func writeFlagMetadataMap(file *os.File, flagMetadata map[string]*FlagMetadata) {
	_, _ = fmt.Fprintln(file, "// Flags contains metadata for all flags from commands.yaml")
	_, _ = fmt.Fprintln(file, "var Flags = map[string]FlagInfo{")

	flagNames := getSortedFlagNames(flagMetadata)
	for _, flagName := range flagNames {
		metadata := flagMetadata[flagName]
		constName := "Flag" + toPascalCase(flagName)
		writeFlagEntry(file, constName, metadata)
	}
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)
}

func writeFlagEntry(file *os.File, constName string, metadata *FlagMetadata) {
	_, _ = fmt.Fprintf(file, "\t%s: {\n", constName)
	_, _ = fmt.Fprintf(file, "\t\tName:        %s,\n", constName)
	_, _ = fmt.Fprintf(file, "\t\tType:        %q,\n", metadata.Type)
	_, _ = fmt.Fprintf(file, "\t\tShort:       %q,\n", metadata.Short)
	_, _ = fmt.Fprintf(file, "\t\tDescription: %q,\n", escapeString(metadata.Description))

	writeDefaultValue(file, metadata.Default)
	writeOptions(file, metadata.Options)
	writeCommands(file, metadata.Commands)

	_, _ = fmt.Fprintf(file, "\t\tIsGlobal:    %t,\n", metadata.IsGlobal)
	_, _ = fmt.Fprintf(file, "\t},\n")
}

func writeDefaultValue(file *os.File, defaultVal any) {
	if defaultVal == nil {
		_, _ = fmt.Fprintf(file, "\t\tDefault:     nil,\n")
		return
	}

	switch v := defaultVal.(type) {
	case bool:
		_, _ = fmt.Fprintf(file, "\t\tDefault:     %t,\n", v)
	case string:
		_, _ = fmt.Fprintf(file, "\t\tDefault:     %q,\n", v)
	case int:
		_, _ = fmt.Fprintf(file, "\t\tDefault:     %d,\n", v)
	case float64:
		if v == float64(int(v)) {
			_, _ = fmt.Fprintf(file, "\t\tDefault:     %d,\n", int(v))
		} else {
			_, _ = fmt.Fprintf(file, "\t\tDefault:     %g,\n", v)
		}
	default:
		_, _ = fmt.Fprintf(file, "\t\tDefault:     nil,\n")
	}
}

func writeOptions(file *os.File, options []string) {
	if len(options) == 0 {
		_, _ = fmt.Fprintf(file, "\t\tOptions:     nil,\n")
		return
	}

	_, _ = fmt.Fprintf(file, "\t\tOptions:     []string{")
	for i, option := range options {
		if i > 0 {
			_, _ = fmt.Fprintf(file, ", ")
		}
		_, _ = fmt.Fprintf(file, "%q", option)
	}
	_, _ = fmt.Fprintf(file, "},\n")
}

func writeCommands(file *os.File, commands []string) {
	if len(commands) == 0 {
		_, _ = fmt.Fprintf(file, "\t\tCommands:    nil,\n")
		return
	}

	_, _ = fmt.Fprintf(file, "\t\tCommands:    []string{")
	for i, cmd := range commands {
		if i > 0 {
			_, _ = fmt.Fprintf(file, ", ")
		}
		_, _ = fmt.Fprintf(file, "%q", cmd)
	}
	_, _ = fmt.Fprintf(file, "},\n")
}

func writeCommandConstants(file *os.File, commandConfig *pkgConfig.CommandConfig) {
	_, _ = fmt.Fprintln(file, "// Command name constants")
	_, _ = fmt.Fprintln(file, "const (")

	cmdNames := getSortedCommandNames(commandConfig)
	for _, cmdName := range cmdNames {
		constName := "Command" + toPascalCase(cmdName)
		_, _ = fmt.Fprintf(file, "\t%s = %q\n", constName, cmdName)
	}
	_, _ = fmt.Fprintln(file, ")")
	_, _ = fmt.Fprintln(file)
}

func writeCommandMetadataMap(file *os.File, commandConfig *pkgConfig.CommandConfig) {
	_, _ = fmt.Fprintln(file, "// Commands contains metadata for all commands")
	_, _ = fmt.Fprintln(file, "var Commands = map[string]CommandInfo{")

	cmdNames := getSortedCommandNames(commandConfig)
	for _, cmdName := range cmdNames {
		writeCommandEntry(file, cmdName, commandConfig)
	}
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)
}

func writeCommandEntry(file *os.File, cmdName string, commandConfig *pkgConfig.CommandConfig) {
	cmd := commandConfig.Commands[cmdName]
	constName := "Command" + toPascalCase(cmdName)

	_, _ = fmt.Fprintf(file, "\t%s: {\n", constName)
	_, _ = fmt.Fprintf(file, "\t\tName: %s,\n", constName)
	_, _ = fmt.Fprintf(file, "\t\tCategory: %q,\n", cmd.Category)
	_, _ = fmt.Fprintf(file, "\t\tHandler: %q,\n", cmd.Handler)
	_, _ = fmt.Fprintf(file, "\t\tDescription: %q,\n", escapeString(cmd.Description))

	flags := getCommandFlags(cmdName, commandConfig)
	writeCommandFlags(file, flags)

	_, _ = fmt.Fprintf(file, "\t},\n")
}

func getCommandFlags(cmdName string, commandConfig *pkgConfig.CommandConfig) []string {
	var flags []string
	cmd := commandConfig.Commands[cmdName]

	for flagName := range cmd.Flags {
		flags = append(flags, "Flag"+toPascalCase(flagName))
	}
	for flagName := range commandConfig.Global.Flags {
		flags = append(flags, "Flag"+toPascalCase(flagName))
	}

	sort.Strings(flags)
	return flags
}

func writeCommandFlags(file *os.File, flags []string) {
	if len(flags) == 0 {
		_, _ = fmt.Fprintf(file, "\t\tFlags: nil,\n")
		return
	}

	_, _ = fmt.Fprintf(file, "\t\tFlags: []string{")
	for i, flag := range flags {
		if i > 0 {
			_, _ = fmt.Fprintf(file, ", ")
		}
		_, _ = fmt.Fprintf(file, "%s", flag)
	}
	_, _ = fmt.Fprintf(file, "},\n")
}

func getSortedCommandNames(commandConfig *pkgConfig.CommandConfig) []string {
	var cmdNames []string
	for cmdName := range commandConfig.Commands {
		cmdNames = append(cmdNames, cmdName)
	}
	sort.Strings(cmdNames)
	return cmdNames
}

func writeHelperFunctions(file *os.File) {
	// Write universal flag parser
	_, _ = fmt.Fprintln(file, "// parseFlags uses reflection to parse all flags in a struct")
	_, _ = fmt.Fprintln(file, "func parseFlags(cmd *cobra.Command, flags interface{}) error {")
	_, _ = fmt.Fprintln(file, "\tv := reflect.ValueOf(flags).Elem()")
	_, _ = fmt.Fprintln(file, "\tt := v.Type()")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "\tfor i := 0; i < v.NumField(); i++ {")
	_, _ = fmt.Fprintln(file, "\t\tfield := v.Field(i)")
	_, _ = fmt.Fprintln(file, "\t\tfieldType := t.Field(i)")
	_, _ = fmt.Fprintln(file, "\t\tflagName := fieldType.Tag.Get(\"flag\")")
	_, _ = fmt.Fprintln(file, "\t\tif flagName == \"\" {")
	_, _ = fmt.Fprintln(file, "\t\t\tcontinue")
	_, _ = fmt.Fprintln(file, "\t\t}")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "\t\tswitch field.Kind() {")
	_, _ = fmt.Fprintln(file, "\t\tcase reflect.Bool:")
	_, _ = fmt.Fprintln(file, "\t\t\tval, err := cmd.Flags().GetBool(flagName)")
	_, _ = fmt.Fprintln(file, "\t\t\tif err != nil {")
	_, _ = fmt.Fprintln(file, "\t\t\t\treturn fmt.Errorf(\"failed to get flag \"+flagName+\": %w\", err)")
	_, _ = fmt.Fprintln(file, "\t\t\t}")
	_, _ = fmt.Fprintln(file, "\t\t\tfield.SetBool(val)")
	_, _ = fmt.Fprintln(file, "\t\tcase reflect.String:")
	_, _ = fmt.Fprintln(file, "\t\t\tval, err := cmd.Flags().GetString(flagName)")
	_, _ = fmt.Fprintln(file, "\t\t\tif err != nil {")
	_, _ = fmt.Fprintln(file, "\t\t\t\treturn fmt.Errorf(\"failed to get flag \"+flagName+\": %w\", err)")
	_, _ = fmt.Fprintln(file, "\t\t\t}")
	_, _ = fmt.Fprintln(file, "\t\t\tfield.SetString(val)")
	_, _ = fmt.Fprintln(file, "\t\tcase reflect.Int:")
	_, _ = fmt.Fprintln(file, "\t\t\tval, err := cmd.Flags().GetInt(flagName)")
	_, _ = fmt.Fprintln(file, "\t\t\tif err != nil {")
	_, _ = fmt.Fprintln(file, "\t\t\t\treturn fmt.Errorf(\"failed to get flag \"+flagName+\": %w\", err)")
	_, _ = fmt.Fprintln(file, "\t\t\t}")
	_, _ = fmt.Fprintln(file, "\t\t\tfield.SetInt(int64(val))")
	_, _ = fmt.Fprintln(file, "\t\t}")
	_, _ = fmt.Fprintln(file, "\t}")
	_, _ = fmt.Fprintln(file, "\treturn nil")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	// Original helper functions
	_, _ = fmt.Fprintln(file, "// GetFlagInfo returns the metadata for a flag")
	_, _ = fmt.Fprintln(file, "func GetFlagInfo(name string) (FlagInfo, bool) {")
	_, _ = fmt.Fprintln(file, "\tinfo, exists := Flags[name]")
	_, _ = fmt.Fprintln(file, "\treturn info, exists")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "// ValidateFlagValue validates a flag value against its constraints")
	_, _ = fmt.Fprintln(file, "func ValidateFlagValue(name string, value interface{}) error {")
	_, _ = fmt.Fprintln(file, "\tinfo, exists := Flags[name]")
	_, _ = fmt.Fprintln(file, "\tif !exists {")
	_, _ = fmt.Fprintf(file, "\t\treturn fmt.Errorf(\"unknown flag: %%s\", name)\n")
	_, _ = fmt.Fprintln(file, "\t}")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "\tif len(info.Options) > 0 && info.Type == \"string\" {")
	_, _ = fmt.Fprintln(file, "\t\tstr, ok := value.(string)")
	_, _ = fmt.Fprintln(file, "\t\tif !ok {")
	_, _ = fmt.Fprintf(file, "\t\t\treturn fmt.Errorf(\"flag %%s expects string value\", name)\n")
	_, _ = fmt.Fprintln(file, "\t\t}")
	_, _ = fmt.Fprintln(file, "\t\tfor _, option := range info.Options {")
	_, _ = fmt.Fprintln(file, "\t\t\tif str == option {")
	_, _ = fmt.Fprintln(file, "\t\t\t\treturn nil")
	_, _ = fmt.Fprintln(file, "\t\t\t}")
	_, _ = fmt.Fprintln(file, "\t\t}")
	_, _ = fmt.Fprintf(file, "\t\treturn fmt.Errorf(\"invalid value '%%s' for flag %%s. Options: %%v\", str, name, info.Options)\n")
	_, _ = fmt.Fprintln(file, "\t}")
	_, _ = fmt.Fprintln(file, "\treturn nil")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)

	_, _ = fmt.Fprintln(file, "// GetFlagsForCommand returns all flags available for a specific command")
	_, _ = fmt.Fprintln(file, "func GetFlagsForCommand(command string) []FlagInfo {")
	_, _ = fmt.Fprintln(file, "\tvar result []FlagInfo")
	_, _ = fmt.Fprintln(file, "\tfor _, flag := range Flags {")
	_, _ = fmt.Fprintln(file, "\t\tif flag.IsGlobal {")
	_, _ = fmt.Fprintln(file, "\t\t\tresult = append(result, flag)")
	_, _ = fmt.Fprintln(file, "\t\t\tcontinue")
	_, _ = fmt.Fprintln(file, "\t\t}")
	_, _ = fmt.Fprintln(file, "\t\tfor _, cmd := range flag.Commands {")
	_, _ = fmt.Fprintln(file, "\t\t\tif cmd == command {")
	_, _ = fmt.Fprintln(file, "\t\t\t\tresult = append(result, flag)")
	_, _ = fmt.Fprintln(file, "\t\t\t\tbreak")
	_, _ = fmt.Fprintln(file, "\t\t\t}")
	_, _ = fmt.Fprintln(file, "\t\t}")
	_, _ = fmt.Fprintln(file, "\t}")
	_, _ = fmt.Fprintln(file, "\treturn result")
	_, _ = fmt.Fprintln(file, "}")
}

func getSortedFlagNames(flagMetadata map[string]*FlagMetadata) []string {
	var flagNames []string
	for flagName := range flagMetadata {
		flagNames = append(flagNames, flagName)
	}
	sort.Strings(flagNames)
	return flagNames
}
func toPascalCase(s string) string {
	// Handle special cases
	switch s {
	case "json":
		return "JSON"
	case "tty":
		return "TTY"
	}

	parts := strings.Split(s, "-")
	for i, part := range parts {
		if len(part) > 0 {
			// Handle special acronyms
			switch strings.ToLower(part) {
			case "json":
				parts[i] = "JSON"
			case "tty":
				parts[i] = "TTY"
			default:
				parts[i] = strings.ToUpper(part[:1]) + strings.ToLower(part[1:])
			}
		}
	}
	return strings.Join(parts, "")
}

// escapeString escapes quotes and newlines in strings for Go code generation
func escapeString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	s = strings.ReplaceAll(s, "\t", "\\t")
	return s
}

func writeCommandParser(file *os.File, cmdName string, cmd pkgConfig.Command, config *pkgConfig.CommandConfig) {
	structName := toPascalCase(cmdName) + "Flags"
	funcName := "Parse" + toPascalCase(cmdName) + "Flags"

	flagFields := collectCommandFlags(cmd, config)

	writeParserStruct(file, structName, flagFields)
	writeParserFunction(file, funcName, structName, flagFields)
}

func writeParserStruct(file *os.File, structName string, flagFields []flagField) {
	_, _ = fmt.Fprintf(file, "type %s struct {\n", structName)
	for _, field := range flagFields {
		_, _ = fmt.Fprintf(file, "\t%s %s `flag:\"%s\"`\n", field.Name, field.Type, field.FlagName)
		if field.FlagName == "timeout" && field.YAMLType == constants.TypeInt {
			_, _ = fmt.Fprintf(file, "\t%sDuration time.Duration\n", field.Name)
		}
	}
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)
}

func writeParserFunction(file *os.File, funcName, structName string, flagFields []flagField) {
	_, _ = fmt.Fprintf(file, "func %s(cmd *cobra.Command) (*%s, error) {\n", funcName, structName)
	_, _ = fmt.Fprintf(file, "\tflags := &%s{}\n", structName)
	_, _ = fmt.Fprintln(file, "\tif err := parseFlags(cmd, flags); err != nil {")
	_, _ = fmt.Fprintln(file, "\t\treturn nil, err")
	_, _ = fmt.Fprintln(file, "\t}")
	_, _ = fmt.Fprintln(file)

	for _, field := range flagFields {
		if field.FlagName == "timeout" && field.YAMLType == constants.TypeInt {
			_, _ = fmt.Fprintf(file, "\tflags.%sDuration = time.Duration(flags.%s) * time.Second\n", field.Name, field.Name)
		}
	}

	_, _ = fmt.Fprintln(file, "\treturn flags, nil")
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)
}

func writeSimpleFlagParsing(file *os.File, field flagField) {
	constName := "Flag" + toPascalCase(field.FlagName)
	switch field.YAMLType {
	case constants.TypeBool:
		_, _ = fmt.Fprintf(file, "\tflags.%s, err = getBoolFlag(cmd, %s)\n", field.Name, constName)
	case constants.TypeString:
		_, _ = fmt.Fprintf(file, "\tflags.%s, err = getStringFlag(cmd, %s)\n", field.Name, constName)
	case constants.TypeInt:
		_, _ = fmt.Fprintf(file, "\tflags.%s, err = getIntFlag(cmd, %s)\n", field.Name, constName)
	}
	_, _ = fmt.Fprintln(file, "\tif err != nil {")
	_, _ = fmt.Fprintln(file, "\t\treturn nil, err")
	_, _ = fmt.Fprintln(file, "\t}")
	_, _ = fmt.Fprintln(file)
}

func collectCommandFlags(cmd pkgConfig.Command, config *pkgConfig.CommandConfig) []flagField {
	var flagFields []flagField

	for flagName, flag := range cmd.Flags {
		flagFields = append(flagFields, flagField{
			Name:     toPascalCase(flagName),
			Type:     goTypeFromYAML(flag.Type),
			FlagName: flagName,
			YAMLType: flag.Type,
		})
	}

	for flagName, flag := range config.Global.Flags {
		if !flagExists(flagFields, flagName) {
			flagFields = append(flagFields, flagField{
				Name:     toPascalCase(flagName),
				Type:     goTypeFromYAML(flag.Type),
				FlagName: flagName,
				YAMLType: flag.Type,
			})
		}
	}

	return flagFields
}

func flagExists(fields []flagField, flagName string) bool {
	for _, field := range fields {
		if field.FlagName == flagName {
			return true
		}
	}
	return false
}

func writeFlagParsing(file *os.File, field flagField) {
	constName := "Flag" + toPascalCase(field.FlagName)
	switch field.YAMLType {
	case constants.TypeBool:
		_, _ = fmt.Fprintf(file, "\tif flags.%s, err = cmd.Flags().GetBool(%s); err != nil {\n", field.Name, constName)
	case constants.TypeString:
		_, _ = fmt.Fprintf(file, "\tif flags.%s, err = cmd.Flags().GetString(%s); err != nil {\n", field.Name, constName)
	case constants.TypeInt:
		_, _ = fmt.Fprintf(file, "\tif flags.%s, err = cmd.Flags().GetInt(%s); err != nil {\n", field.Name, constName)
	}
	_, _ = fmt.Fprintf(file, "\t\treturn nil, fmt.Errorf(\"failed to get %s flag: %%w\", err)\n", field.FlagName)
	_, _ = fmt.Fprintln(file, "\t}")
	_, _ = fmt.Fprintln(file)
}

// flagField represents a field in a generated flag struct
type flagField struct {
	Name     string
	Type     string
	FlagName string
	YAMLType string
}

// goTypeFromYAML converts YAML types to Go types
func goTypeFromYAML(yamlType string) string {
	switch yamlType {
	case constants.TypeBool:
		return constants.TypeBool
	case constants.TypeString:
		return constants.TypeString
	case constants.TypeInt:
		return constants.TypeInt
	default:
		return "interface{}"
	}
}

func collectMessageMetadata(commandConfig *pkgConfig.CommandConfig) map[string]string {
	messages := make(map[string]string)
	if commandConfig.Messages == nil {
		return messages
	}

	for category, categoryData := range commandConfig.Messages {
		categoryMap := categoryData.(map[string]any)
		for key, value := range categoryMap {
			messages[category+"."+key] = value.(string)
		}
	}
	return messages
}

func collectIconMetadata(commandConfig *pkgConfig.CommandConfig) map[string]string {
	icons := make(map[string]string)
	if commandConfig.Icons == nil {
		return icons
	}

	for category, categoryData := range commandConfig.Icons {
		categoryMap := categoryData.(map[string]any)
		for key, value := range categoryMap {
			icons[category+"."+key] = value.(string)
		}
	}
	return icons
}

func writeMessageConstants(file *os.File, messageMetadata map[string]string) {
	if len(messageMetadata) == 0 {
		return
	}

	_, _ = fmt.Fprintln(file, "// Message key constants")
	_, _ = fmt.Fprintln(file, "const (")

	for msgKey := range messageMetadata {
		constName := "Msg" + toPascalCase(strings.ReplaceAll(msgKey, ".", "_"))
		_, _ = fmt.Fprintf(file, "\t%s = %q\n", constName, msgKey)
	}
	_, _ = fmt.Fprintln(file, ")")
	_, _ = fmt.Fprintln(file)
}

func writeMessageMetadataMap(file *os.File, messageMetadata map[string]string) {
	if len(messageMetadata) == 0 {
		return
	}

	_, _ = fmt.Fprintln(file, "// Messages contains all messages from commands.yaml")
	_, _ = fmt.Fprintln(file, "var Messages = map[string]string{")

	for msgKey, msgValue := range messageMetadata {
		constName := "Msg" + toPascalCase(strings.ReplaceAll(msgKey, ".", "_"))
		_, _ = fmt.Fprintf(file, "\t%s: %q,\n", constName, escapeString(msgValue))
	}
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)
}

func writeIconConstants(file *os.File, iconMetadata map[string]string) {
	if len(iconMetadata) == 0 {
		return
	}

	_, _ = fmt.Fprintln(file, "// Icon key constants")
	_, _ = fmt.Fprintln(file, "const (")

	for iconKey := range iconMetadata {
		constName := "Icon" + toPascalCase(strings.ReplaceAll(iconKey, ".", "_"))
		_, _ = fmt.Fprintf(file, "\t%s = %q\n", constName, iconKey)
	}
	_, _ = fmt.Fprintln(file, ")")
	_, _ = fmt.Fprintln(file)
}

func writeIconMetadataMap(file *os.File, iconMetadata map[string]string) {
	if len(iconMetadata) == 0 {
		return
	}

	writeIconConstants(file, iconMetadata)

	_, _ = fmt.Fprintln(file, "// Icons contains all icons from commands.yaml")
	_, _ = fmt.Fprintln(file, "var Icons = map[string]string{")

	for iconKey, iconValue := range iconMetadata {
		constName := "Icon" + toPascalCase(strings.ReplaceAll(iconKey, ".", "_"))
		_, _ = fmt.Fprintf(file, "\t%s: %q,\n", constName, iconValue)
	}
	_, _ = fmt.Fprintln(file, "}")
	_, _ = fmt.Fprintln(file)
}
